name: Sync downloads to VDS

on:
  release:
    types: [published]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync files to VDS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_SSH_KEY }}
          script: /opt/unspace/sync.sh >> /var/log/unspace-sync.log 2>&1